# docker compose up --scale api=2 -d --build
# migrate data in database.sql first
# http://localhost:8081/swagger/index.html
# 
version: '3.4'

services:
  database:    
    # image: mcr.microsoft.com/mssql/server:2022-latest (for intel)
    # image: mcr.microsoft.com/azure-sql-edge (for apple sillicon)
    image: mcr.microsoft.com/azure-sql-edge
    container_name: database            
    environment:
      SA_PASSWORD: Mflv[Mflv[
      ACCEPT_EULA: Y
    volumes:    
      - ./db:/var/opt/mssql    
    ports:
      - 1433:1433    
  api:
    image: backend    
    depends_on:
      - database    
    build:
      context: .
      dockerfile: ./Dockerfile    
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - api
    ports:
      - 8081:8081
    volumes:
      - ./conf.d:/etc/nginx/conf.d
          
