# docker compose up --scale api=2 -d --build
# migrate data in database.sql first
# http://localhost:8081/swagger/index.html
# 
version: '3.4'

services:    
  api:
    image: backend        
    ports:
      - 8085:8081
    build:
      context: .
      dockerfile: ./Dockerfile 